### ISSUE TITLE
Unsupported oat version: 45

### ISSUE THREAD

**Issue by pinigtech** [aureljared/simple-deodexer#5]
Is that error coming because the included oat2dex.jar is not right or the file I am de odexing is a non compatible version?

**Comment by jareddantis** [comment]
Hi, files from Lollipop are currently unsupported due to oat2dex and baksmali/smali not supporting the Lollipop oat format (see https://github.com/aureljared/simple-deodexer/issues/3#issuecomment-355808661).

You might have some luck with other deodexers.
